# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: /home/thayer/workspace/module1/module1.srcs/sources_1/bd/module1_hw/ip/module1_hw_processing_system7_0_0/module1_hw_processing_system7_0_0.xci
# IP: The module: 'module1_hw_processing_system7_0_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: /home/thayer/workspace/module1/module1.gen/sources_1/bd/module1_hw/ip/module1_hw_processing_system7_0_0/module1_hw_processing_system7_0_0.xdc
# XDC: The top module name and the constraint reference have the same name: 'module1_hw_processing_system7_0_0'. Do not add the DONT_TOUCH constraint.
set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# IP: /home/thayer/workspace/module1/module1.srcs/sources_1/bd/module1_hw/ip/module1_hw_processing_system7_0_0/module1_hw_processing_system7_0_0.xci
# IP: The module: 'module1_hw_processing_system7_0_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: /home/thayer/workspace/module1/module1.gen/sources_1/bd/module1_hw/ip/module1_hw_processing_system7_0_0/module1_hw_processing_system7_0_0.xdc
# XDC: The top module name and the constraint reference have the same name: 'module1_hw_processing_system7_0_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet
